FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY src/index.html /usr/share/nginx/html/
COPY src/app.js /usr/share/nginx/html/
COPY deployment/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]